name: Test and publish

on:
  push:
    tags:
      - "*"

jobs:
  test:
    uses: theOGognf/rlstack/.github/workflows/test.yml@main
    secrets: inherit

  publish:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tox
        run: pip install tox
      - name: Build
        run: tox -e build
      - name: Publish
        run: tox -e publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
          TWIN_REPOSITORY: pypi
